name: push to dockerhub

on:
  push:
    # run only if a tag is pushed
    branches:
      - master
    tags:
      - '*'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the Docker base image version
        id: vars
        run: echo ::set-output name=alpine::$(echo ${tac Dockerfile | grep -m 1 ^FROM | cut -d - -f 2)

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build the tagged Docker image
        run: |
          docker build . --tag kmille2/deezer-downloader:${{steps.vars.outputs.alpine}}-${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push kmille2/deezer-downloader:${{steps.vars.outputs.tag}}

      - name: Build the latest Docker image
        run: |
          docker build . --tag kmille2/deezer-downloader:latest
      - name: Push the latest Docker image
        run: docker push kmille2/deezer-downloader:latest
